### ISSUE TITLE
Cannot GET /downloads/

### ISSUE THREAD

**Issue by baba2580** [xinxin8816/heroku-ariang-21vianet#11]
Inserted APP Secret clicked on view download files get this msg 

Cannot GET /downloads/YmFiYTFAaGVyb2t1/

**Comment by xinxin8816** [comment]
Two possible reasons:
1. Wrong APP secret.
2. There have no tasks completed.
Check it.

**Comment by baba2580** [comment]
i checked it
Right APP secret
tasks completed
Getting Error
After put Right APP secret
Cannot GET /downloads/YmFiYTFAaGVyb2t1/
without APP secret
Cannot GET /downloads//

**Comment by xinxin8816** [comment]
Please try to deploy by this old version https://github.com/xinxin8816/heroku-ariang-21vianet/tree/b7cc2174bd3a0cbd47c3bf7683c751004c79c8b2

**Comment by baba2580** [comment]
Same Error

Cannot GET /downloads/YmFiYTFAaGVyb2t1/

**Comment by baba2580** [comment]
2020-05-20T11:14:40.440855+00:00 app[web.1]:     at Request.self.callback (/app/node_modules/request/request.js:185:22)
2020-05-20T11:14:40.440856+00:00 app[web.1]:     at Request.emit (events.js:310:20)
2020-05-20T11:14:40.440856+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)
2020-05-20T11:14:40.440856+00:00 app[web.1]:     at Request.emit (events.js:310:20)
2020-05-20T11:14:40.440857+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)
2020-05-20T11:14:40.440858+00:00 app[web.1]:     at Object.onceWrapper (events.js:416:28)
2020-05-20T11:14:40.440858+00:00 app[web.1]:     at IncomingMessage.emit (events.js:322:22)
2020-05-20T11:14:40.440859+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:1187:12)
2020-05-20T11:14:40.440859+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-05-20T11:14:40.440994+00:00 app[web.1]: (node:49) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**Comment by xinxin8816** [comment]
Interesting, But this issue is beyond my support.
Please feedback this issue at the source of Fork [Heroku-Aria2c issues](https://github.com/maple3142/heroku-aria2c/issues)

**Comment by xinxin8816** [comment]
I tested the source fork and my APP, no occur this bugs. And I have discussed with maple3142, this may be your problem when deployed, try to rebuild step by step with README, sorry we can't solve the issue.
