### ISSUE TITLE
app crash and stops all concurrent downloads

### ISSUE THREAD

**Issue by cocoamartin** [xinxin8816/heroku-ariang-21vianet#18]
I always has this warning: (node:50) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

an then a depreciation warning and app stops all downloads

2020-06-12T20:24:53.009332+00:00 heroku[web.1]: Unidling
2020-06-12T20:24:53.018202+00:00 heroku[web.1]: State changed from down to starting
2020-06-12T20:24:57.145113+00:00 heroku[web.1]: Starting process with command `source setup.sh && bash start.sh`
2020-06-12T20:25:04.334542+00:00 app[web.1]: Rclone config detected
2020-06-12T20:25:05.136749+00:00 app[web.1]: yarn run v1.22.4
2020-06-12T20:25:05.212481+00:00 app[web.1]: $ node index.js
2020-06-12T20:25:06.396176+00:00 app[web.1]: Listening on http://localhost:10571
2020-06-12T20:25:06.768841+00:00 heroku[web.1]: State changed from starting to up
2020-06-12T20:25:08.343120+00:00 app[web.1]: preventIdling: getGlobalStat response {
2020-06-12T20:25:08.343130+00:00 app[web.1]:   id: 'preventIdling',
2020-06-12T20:25:08.343131+00:00 app[web.1]:   jsonrpc: '2.0',
2020-06-12T20:25:08.343132+00:00 app[web.1]:   error: { code: 1, message: 'Unauthorized' }
2020-06-12T20:25:08.343132+00:00 app[web.1]: }
2020-06-12T20:25:08.344902+00:00 app[web.1]: (node:50) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'numActive' of 'body.result' as it is undefined.
2020-06-12T20:25:08.344903+00:00 app[web.1]:     at Request._callback (/app/index.js:60:13)
2020-06-12T20:25:08.344904+00:00 app[web.1]:     at Request.self.callback (/app/node_modules/request/request.js:185:22)
2020-06-12T20:25:08.344904+00:00 app[web.1]:     at Request.emit (events.js:315:20)
2020-06-12T20:25:08.344904+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/request/request.js:1154:10)
2020-06-12T20:25:08.344905+00:00 app[web.1]:     at Request.emit (events.js:315:20)
2020-06-12T20:25:08.344906+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1076:12)
2020-06-12T20:25:08.344906+00:00 app[web.1]:     at Object.onceWrapper (events.js:421:28)
2020-06-12T20:25:08.344906+00:00 app[web.1]:     at IncomingMessage.emit (events.js:327:22)
2020-06-12T20:25:08.344907+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:1224:12)
2020-06-12T20:25:08.344907+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-06-12T20:25:08.344908+00:00 app[web.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2020-06-12T20:25:08.345011+00:00 app[web.1]: (node:50) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2020-06-12T20:25:08.345128+00:00 app[web.1]: (node:50) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by xinxin8816** [comment]
It seems Prevent Idling feature cann't connect build-in Aria2c because of error: { code: 1, message: 'Unauthorized' }

Try to change `ARIA2C_SECRET`, and make sure `HEROKU_APP_NAME` is the same as `App name`.
If it still not work, try to turn off Prevent Idling feature: delete preventIdling() in index.js at line 81.
